import { NextRequest, NextResponse } from 'next/server';

const SYSTEM_PROMPT = `You are an expert Kubernetes engineer. Given a user's description, generate production-ready Kubernetes YAML manifests.

Rules:
- Always include resource limits and requests
- Add appropriate labels (app, version)
- Include health checks (liveness/readiness probes) where applicable
- Use latest stable API versions
- Add comments explaining non-obvious choices
- If multiple resources are needed (e.g., Deployment + Service), separate them with ---
- Follow security best practices (non-root, read-only filesystem where possible)
- Output ONLY valid YAML, no markdown fences, no explanation text`;

export async function POST(req: NextRequest) {
  try {
    const { prompt } = await req.json();

    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
    }

    const apiKey = process.env.DEEPSEEK_API_KEY || process.env.OPENAI_API_KEY;
    
    if (!apiKey) {
      return NextResponse.json({
        yaml: generateSampleYaml(prompt),
        demo: true,
      });
    }

    const baseUrl = process.env.DEEPSEEK_API_KEY
      ? 'https://api.deepseek.com/v1/chat/completions'
      : 'https://api.openai.com/v1/chat/completions';
    const model = process.env.DEEPSEEK_API_KEY ? 'deepseek-chat' : 'gpt-4o-mini';

    const response = await fetch(baseUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: prompt },
        ],
        temperature: 0.1,
        max_tokens: 2000,
      }),
    });

    const data = await response.json();
    const yaml = data.choices?.[0]?.message?.content || 'Error generating YAML';

    return NextResponse.json({ yaml });
  } catch (error) {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

function generateSampleYaml(prompt: string): string {
  const lower = prompt.toLowerCase();
  const name = lower.includes('nginx') ? 'nginx' : lower.includes('redis') ? 'redis' : 'my-app';
  const image = lower.includes('nginx') ? 'nginx:1.25-alpine' : lower.includes('redis') ? 'redis:7-alpine' : 'my-app:latest';
  const port = lower.includes('80') ? 80 : lower.includes('8080') ? 8080 : lower.includes('6379') ? 6379 : 8080;
  const replicas = lower.match(/(\d+)\s*replica/)?.[1] || '2';

  return `# Generated by KubeHelper (demo mode)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    app: ${name}
    version: v1
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
        version: v1
    spec:
      containers:
        - name: ${name}
          image: ${image}
          ports:
            - containerPort: ${port}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: ${port}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: ${port}
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  labels:
    app: ${name}
spec:
  type: ClusterIP
  ports:
    - port: ${port}
      targetPort: ${port}
  selector:
    app: ${name}`;
}
